import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "rohit",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: true,
    },
    {
      name: "john",
      email: "john@example.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim shirts",
      category: "Shirts",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numRating: 10,
      description: "Hign quality products",
    },
    {
      name: "Addidas shirt",
      category: "Shirts",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 0,
      brand: "Addidas",
      rating: 4,
      numRating: 10,
      description: "Hign quality products",
    },
    {
      name: "Puma pants",
      category: "pants",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Puma",
      rating: 3,
      numRating: 10,
      description: "Hign quality products",
    },
    {
      name: "Raymond shirt",
      category: "Shirts",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Raymond",
      rating: 4.5,
      numRating: 10,
      description: "Hign quality products",
    },
    {
      name: "Nike Trowser",
      category: "Trowsers",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numRating: 10,
      description: "Hign quality products",
    },
    {
      name: "Wrangler pants",
      category: "Pants",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Wrangler",
      rating: 1,
      numRating: 10,
      description: "Hign quality products",
    },
    {
      name: "Nike Slim shirts 2",
      category: "Shirts",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "nike",
      rating: 4.5,
      numRating: 10,
      description: "Hign quality products",
    },
    {
      name: "Nike Slim shirts 4",
      category: "Shirts",
      image: "images/product-1.jpg",
      price: 120,
      countInStock: 0,
      brand: "nike",
      rating: 4.5,
      numRating: 10,
      description: "Hign quality products",
    },
  ],
};

export default data;
